### PR TITLE
chore: update README contributions

### PR DESCRIPTION
**Pull request by ariperez**
@BrandonClapp , I'll leave this as a draft as I try to capture and evolve the CONTRIBUTION process we are co-creating here.

### CODE REVIEW

**Comment by BrandonClapp** [comment]
Sounds good. 

How do we want to handle merges to `main`? Each person merge their own after approval or have one person (you) dedicated to merging? I'm indifferent.

**Comment by ariperez** [comment]
I always go with the approver merging right after approval.

**Comment by ariperez** [comment]
Official Chromatic steps...https://www.chromatic.com/docs/review#ui-checklist

**Comment by ariperez** [comment]
closing this, will open a new one when we have updates for CONTRIBUTIONS

**Pull request merged**
