### PR TITLE
feat: chromatic viewports

### PR DESCRIPTION
**Pull request by ariperez**

### CODE REVIEW

**Comment by ariperez** [comment]
@BrandonClapp , any strong feelings on what viewport sizes should always be monitored in Chromatic going forward?

image

**Comment by BrandonClapp** [comment]
Nope, not at all. I usually use iPad and iPhone XS resolutions, but that's just because what I use.

So I use 375px for mobile and 768px for tablet, then around 1200px for desktop.

**Comment by ariperez** [comment]
@BrandonClapp , I"ll let you review this at your leisure.  The chromatic review seems more useful with the different viewport sizes included.

https://www.chromatic.com/pullrequest?appId=618c059790d3e7003af59018&number=99

**Comment by BrandonClapp** [comment]
That looks great. I may tweak some of the font sizes on different screen sizes, but this is good.

**Pull request merged**
